#!/bin/sh

set -e

BUILD_DATE="$(date)"

GIT_STATE=''
if [[ $(git diff --stat) != '' ]]; then
  GIT_STATE='-dirty'
  echo "git state: DIRTY, please commit!"
fi

BUILD_HASH="$(git rev-parse HEAD)${GIT_STATE}"
BUILD_AGENT="local"
VERSION="1.0.1"
NAME=ngress
REGISTRY=allright
IMAGE=$REGISTRY/$NAME

echo "IMAGE: $IMAGE"
echo "GIT_HASH: $BUILD_HASH"
echo "BUILD_DATE: $BUILD_DATE"
echo "VERSION: $VERSION"

docker buildx build -f ./Dockerfile . \
--progress=plain \
--build-arg VERSION=$VERSION \
--build-arg HASH="$BUILD_HASH" \
--build-arg BUILD_DATE="$BUILD_DATE" \
--build-arg BUILD_AGENT="$BUILD_AGENT" \
--platform linux/arm64,linux/amd64 \
--tag $IMAGE:$VERSION \
--tag $IMAGE:latest \
--cache-to type=local,dest=.docker \
--cache-from type=local,src=.docker \
--push

